Enrollment no: 240840116003

Practical-8 Create interactive visulizations using plotly express and plotly graph objects

TASK 1 IMPORT REQUIRED LIBRARIES

In [ ]:
# Import pandas for data manipulation and analysis
import pandas as pd

# Import Plotly Express for quick and easy high-level interactive visualizations
import plotly.express as px

# Import Plotly Graph Objects for highly customized, low-level interactive visualizations
import plotly.graph_objects as go

TASK 2 CREATE THE COMMON DATASET AND INSPECT THE DATA

In [ ]:
# Create the Dataset
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'Product': ['Laptop','Mobile','Tablet','Laptop','Mobile','Tablet','Laptop','Mobile','Tablet','Laptop','Mobile','Tablet'],
    'Region': ['North','South','East','West','North','South','East','West','North','South','East','West'],
    'Sales':[120000,135000,150000,145000,160000,175000,180000,170000,190000,210000,230000,250000],
    'Unit_Sold':[12,30,25,14,35,30,18,38,32,21,45,40],
    'Profit':[18000,27000,30000,22000,32000,35000,28000,34000,38000,33000,46000,50000]
}
# Display the Dataset
df = pd.DataFrame(data)
df

   Month Product Region   Sales  Unit_Sold  Profit
0    Jan  Laptop  North  120000         12   18000
1    Feb  Mobile  South  135000         30   27000
2    Mar  Tablet   East  150000         25   30000
3    Apr  Laptop   West  145000         14   22000
4    May  Mobile  North  160000         35   32000
5    Jun  Tablet  South  175000         30   35000
6    Jul  Laptop   East  180000         18   28000
7    Aug  Mobile   West  170000         38   34000
8    Sep  Tablet  North  190000         32   38000
9    Oct  Laptop  South  210000         21   33000
10   Nov  Mobile   East  230000         45   46000
11   Dec  Tablet   West  250000         40   50000

In [ ]:
# display 1st five rows
df.head()

  Month Product Region   Sales  Unit_Sold  Profit
0   Jan  Laptop  North  120000         12   18000
1   Feb  Mobile  South  135000         30   27000
2   Mar  Tablet   East  150000         25   30000
3   Apr  Laptop   West  145000         14   22000
4   May  Mobile  North  160000         35   32000

In [ ]:
# display the number of row and columns
df.shape

(12, 6)

In [ ]:
# display column name and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Month      12 non-null     object
 1   Product    12 non-null     object
 2   Region     12 non-null     object
 3   Sales      12 non-null     int64
 4   Unit_Sold  12 non-null     int64
 5   Profit     12 non-null     int64
dtypes: int64(3), object(3)
memory usage: 708.0+ bytes

TASK 3 CREATE AN INTERACTIVE LINE CHART USING POLTLY EXPRESS

In [ ]:
# How does sales revenue change throughout the year ?
fig = px.line(df, x='Month', y='Sales', title='Sales Revenue Over Time')
fig.show()

TASK 4 IMPROVE THE HOVER INFORMATION

In [ ]:
# Create a line chart using sales over month.
fig = px.line(df, x='Month', y='Sales', title='Sales Revenue Over Time')
fig.update_traces(
    hovertemplate='Month: %{x}<br>Sales: %{y}'
)
fig.show()

In [ ]:
# Add additional columns to the hover information. student can see product, region, unit sold and profit when they move the mouse over a data point.
fig = px.line(df, x='Month', y='Sales', title='Sales Revenue Over Time',
              hover_data=['Unit_Sold', 'Profit'],
              color='Product',
              markers=True)
fig.show()

TASK 5 CREATE AN INTERACTIVE BAR CHART

In [ ]:
# Group the dataset according to product.
df_product = df.groupby('Product')[['Sales', 'Unit_Sold', 'Profit']].sum().reset_index()

# Calculate the total sales generated by each product.
total_sales_by_product = df.groupby('Product')['Sales'].sum().reset_index()
display(total_sales_by_product)

# Create an interactive bar chart
fig = px.bar(total_sales_by_product, x='Product', y='Sales', title='Total Sales by Product')
fig.show()

  Product   Sales
0  Laptop  655000
1  Mobile  695000
2  Tablet  765000

TASK 6 INTERACTIVE SCATTER PLOT

In [ ]:
# To analyze the relationship between units sold and sales using an interactive scatter plot.
fig = px.scatter(df, x='Unit_Sold', y='Sales',
                  title='Relationship between Units Sold and Sales',
                  labels={'Unit_Sold': 'Units Sold', 'Sales': 'Sales ($)'})
fig.show()

TASK 7 INTERACTIVE SCATTER PLOT WITH COLOR

In [ ]:
# we will use region as the color variable.
fig = px.scatter(
    df,
    x='Sales',
    y='Profit',
    color='Region',
    title='Interactive Scatter Plot: Sales vs Profit by Region',
    hover_data=df.columns
)

fig.update_layout(
    xaxis_title='Sales',
    yaxis_title='Profit',
    legend_title='Region',
    template='plotly_white'
)

fig.show()

TASK 8 CREATE AN INTERACTIVE PIE CHART

In [ ]:
#To visualize regional sales contribution using an interactive pie chart.
fig = px.pie(df, names='Region', values='Sales', title='Regional Sales Contribution')
fig.show()

TASK 9 PLOTLY GRAPH OBJECTS

In [ ]:
# To create an interactive visualization using plotly graph objects and understand how it differs from plotly Express.
fig = go.Figure(
    data=[
        go.Scatter(
            x=df['Month'],
            y=df['Sales'],
            mode="lines+markers",
            name="Sales"
        )
    ]
)

fig.update_layout(
    title="Monthly Sales Analysis",
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()

TASK 10 CREATE LINE CHART USING GRAPH OBJECT

In [ ]:
# Create a figure object.
fig = go.Figure()

# Add a line trace to the figure.This trace represents the monthly sales data.
fig.add_trace(
    go.Scatter(
        x=df['Month'],
        y=df['Sales'],
        mode='lines+markers',
        name='Sales'
    )
)

fig.show()